### ISSUE TITLE
Structurize and Lootr Chests

### ISSUE THREAD

**Issue by z64555** [Electrofried/ModColonies#4] opened 2021-06-03 18:33 UTC
Structurize blueprints are able to take snapshots of blocks and tile entities that might be unobtainable, such as the loot chests from Lootr.

I suggest making something akin to an oredictionary to allow placement of ordinary chests or Quark chests instead of the Lootr chest.

**Comment by Electrofried** [comment] 2021-06-04 01:27
I am sorry, I am not understanding the issue here. Yes, Structurize can  take snapshots, but id does not allow you to obtain those items yourself without crafting them correct?
If you are recommending that Structurize adds an ore dictionary feature that is an issue for the [Mod](https://github.com/ldtteam/structurize), not the  ModColonies modpack.

**Comment by z64555** [comment] 2021-06-04 02:12
Structurize asks for the item itself, even if it can not be obtained by the player through normal means.  For the example of the Lootr chests, the Loot chests cannot be crafted nor can they be picked up by the player, they are therefore "unobtainable."

And yeah, I thought it would be something specific to the mod, but it should at least be reported and closed here so that anybody that stumbles across the issue again knows where to be redirected.

**Comment by Electrofried** [comment] 2021-06-04 02:27
This is not a bug, this is the intended function of the mod. If you want you can place down a schematic in creative mode remove the offending items and then re-scan it. If you want structurize to add ore dictionary compatibility for chests or other items then I would report it on their github (though they will probably just close it with "outside scope" because there exists already a way for you to fix this yourself)

**Closed as completed by Electrofried** 2021-06-04 02:27 UTC
Labels: wontfix, mod-issue
